services: 
    Database:
        image: mariadb
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
        ports:
            - '3306:3306'
        volumes:
            - './volumes/MovieSave:/var/lib/mysql'